const cakeData = [{
        name: "Rainbow Pinata",
        amount: 9800,
        inCart: false,
        count: 1,
        image1: "cake-images/cake1.jpg",
        image2: "cake-images/cake13.jpg",
        category: "birthday cake",
        id: 1,
        customerFav: true,
        total: 0,
    },
    {
        name: "Rainbow Pinata",
        amount: 7600,
        inCart: false,
        count: 1,
        image1: "cake-images/cake3.jpg",
        category: "wedding cake",
        id: 2,
        total: 0,
    },
    {
        name: "Crispy cake",
        amount: 2800,
        inCart: false,
        count: 1,
        image1: "cake-images/cake4.jpg",
        image2: "cake-images/cake5.jpg",
        category: "children cake",
        id: 3,
        customerFav: true,
        total: 0,
    },
    {
        name: "Sponge Cake",
        amount: 11100,
        inCart: false,
        count: 1,
        image1: "cake-images/cake6.jpg",
        category: "valentine cake",
        id: 4,
        total: 0,
    },
    {
        name: "Red Velvet Cupcake",
        amount: 2600,
        inCart: false,
        count: 1,
        image1: "cake-images/cake7.jpg",
        image2: "cake-images/cake8.jpg",
        category: "cup cake",
        id: 5,
        customerFav: true,
        total: 0,
    },
    {
        name: "donut",
        amount: 1000,
        inCart: false,
        count: 1,
        image1: "cake-images/cake9.jpg",
        image2: "cake-images/cake10.jpg",
        category: "donut",
        id: 6,
        customerFav: true,
        total: 0,
    },
    {
        name: "Sponge Cake",
        amount: 3600,
        inCart: false,
        count: 1,
        image1: "cake-images/cake11.jpg",
        category: "valentine cake",
        id: 7,
        total: 0,
    },
    {
        name: "Coconut Cake",
        amount: 8600,
        inCart: false,
        count: 1,
        image1: "cake-images/cake12.jpg",
        category: "birthday cake",
        id: 8,
        customerFav: true,
        total: 0,
    },
];


const categories = [
  "Birthday Cake",
  "Wedding Cake",
  "Valentine Cake",
  "Anniversary Cake",
  "Children's Cake",
];

module.exports={
    categories: categories,
    cakeData: cakeData
}